export const SELECT_ROLE = 'SELECT_ROLE'

export const FETCH_TABLE = 'FETCH_TABLE'
export const FETCH_TABLE_BY_ID = 'FETCH_TABLE_BY_ID'
export const CALCULATE_BILL_TOTAL = 'CALCULATE_BILL_TOTAL'
export const CALCULATE_BILL_SUBTOTAL = 'CALCULATE_BILL_SUBTOTAL'
export const CALCULATE_EXCHANGE = 'CALCULATE_EXCHANGE'

export const FETCH_CODES = 'FETCH_CODES'
export const APPLY_CODE = 'APPLY_CODE'
export const REMOVE_CODE = 'REMOVE_CODE'
export const GET_CODE_CASES = 'GET_CODE_CASES'

export const CODE_6000 = 'CODE_6000'
export const CODE_1000 = 'CODE_1000'
export const CODE_4PAY3 = '4PAY3'
export const CODE_LUCKYONE = 'LUCKY ONE'
export const CODE_LUCKYTWO = 'LUCKY TWO'
