export const SELECT_ROLE = 'SELECT_ROLE'

export const FETCH_TABLE = 'FETCH_TABLE'
export const FETCH_TABLE_BY_ID = 'FETCH_TABLE_BY_ID'
export const CALCULATE_BILL_TOTAL = 'CALCULATE_BILL_TOTAL'
export const CALCULATE_BILL_SUBTOTAL = 'CALCULATE_BILL_SUBTOTAL'
export const CALCULATE_EXCHANGE = 'CALCULATE_EXCHANGE'
export const APPLY_CODE = 'APPLY_CODE'
